version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
    container_name: rtmp_server
    env_file:
      - ./env/.env.prod
    volumes:
      - ./rtmp/nginx.conf:/etc/nginx/nginx.conf.template
      - ./rtmp/stdout_http.log:/eliv/logs/stdout_http.log
      - ./rtmp/stdout_rtmp.log:/eliv/logs/stdout_rtmp.log
      - "${RTMP_HLS_VOD_PATH}:${RTMP_HLS_VOD_PATH}"
      - "${RTMP_HLS_RECORD_PATH}:${RTMP_HLS_RECORD_PATH}"
      - "${RTMP_HLS_LIVE_PATH}:${RTMP_HLS_LIVE_PATH}"

  api:
    depends_on:
      - postgres
      - redis
    build: 
      dockerfile: Dockerfile
      context: ./api
      # Only will build development stage from our dockerfile
      target: prod
     # Enables the data to be persisted and is what makes the hot reloading possible.
    volumes:
      # - /usr/src/app/node_modules
      - "${PATH_HLS}:${PATH_HLS}"
    # load the .env file into the container
    env_file:
      - ./env/.env.prod
    ports:
      - "${API_PORT}:${API_PORT}"
    container_name: api_server
  postgres:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - ./env/.env.prod
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /eliv/backup:/eliv/backup
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
  pgdata: