version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
    container_name: rtmp_server
    volumes:
      - ./data:/tmp/hls

  api:
    depends_on:
      - postgres
    build: 
      dockerfile: Dockerfile
      context: ./api
      # Only will build development stage from our dockerfile
      target: dev
     # Enables the data to be persisted and is what makes the hot reloading possible.
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    # load the .env file into the container
    env_file:
      - ./api/.env.docker
    ports:
      - "${API_PORT}:${API_PORT}"
    container_name: api_server
  postgres:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - ./api/.env.docker
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: