name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  

  build:

    runs-on: ubuntu-latest
    permissions:
       contents: 'read'
       id-token: 'write'
    
    steps:
      # actions/checkout MUST come before auth
      - uses: 'actions/checkout@v3'
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/1047923984027/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@sapient-magnet-371415.iam.gserviceaccount.com'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: "Build and deploy docker/Cleanup old images"
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'dnntung@eliv'
          zone: 'asia-southeast1-b'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: |
            cd ~/eliv-api
            git stash
            git pull
            sudo sh deploy-docker.prod.sh
            sudo sh cleanup-docker-image.sh
