name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  

  build:

    runs-on: ubuntu-latest
    permissions:
       contents: 'read'
       id-token: 'write'
    
    steps:
      # actions/checkout MUST come before auth
      - uses: 'actions/checkout@v3'
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/1047923984027/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@sapient-magnet-371415.iam.gserviceaccount.com'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        
      - name: "Running cmd with gcloud"
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'eliv'
          zone: 'asia-southeast1-b'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: 'echo Hello world'
        
#       - name: 'Pull repo src'
#         run: gcloud compute ssh --zone "asia-southeast1-b" "eliv"  --project "sapient-magnet-371415" --command "cd ~/eliv-api && git stash && git pull"
        
          
#       - name: "Build and deploy with Docker"
#         run:  gcloud compute ssh --zone "asia-southeast1-b" "eliv"  --project "sapient-magnet-371415" --command "sh deploy-docker.prod.sh"
        
#       - name: "Cleanup docker unused images"
#         run: gcloud compute ssh --zone "asia-southeast1-b" "eliv"  --project "sapient-magnet-371415" --command "sh cleanup-docker-image.sh"
          
